# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChallengeSicredi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChallengeSicredi
  pod 'Alamofire' , '~> 4.9.1'
  pod 'ObjectMapper'
  pod 'Kingfisher'

  target 'ChallengeSicrediTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChallengeSicrediUITests' do
    # Pods for testing
  end

end
